language: scala
scala:
 - 2.12.4
script:
  - sbt coverage test coverageReport
  - sbt 'set test in assembly := {}' clean assembly
  - zip -r -q api-finatra *
  - mkdir -p dpl_cd_upload
  - mv api-finatra.zip dpl_cd_upload/api-finatra.zip

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: WsCandy/api.finatra
    bucket: finatra
    region: eu-west-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: finatra
    key: api-finatra.zip
    bundle_type: zip
    application: ceer
    deployment_group: ceer-application
    region: eu-west-2
    on: *2